### ISSUE TITLE
ERROR @wdio/config:ConfigParser: 

### ISSUE THREAD

**Issue by horsecoin** [blueimp/wdio#7]
2019-04-30 18:48:20 ☆  nickademous in ~
± |master ↑1 ↓2 S:387 U:367 ?:452 ✗| → docker run -it -v $(pwd):/usr/workspace blueimp/wdio sh
Unable to find image 'blueimp/wdio:latest' locally
latest: Pulling from blueimp/wdio
bdf0201b3a05: Pull complete 
436b67d6d032: Pull complete 
6e7ac5f22b73: Pull complete 
68e94cea041c: Pull complete 
bfe897812e06: Pull complete 
Digest: sha256:5cfcfe1a43ef277e56584b820b8618b0d1744006f3e76292ae53b3bde69f410d
Status: Downloaded newer image for blueimp/wdio:latest
2019-05-01T04:52:45.887Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: /opt/sh: Cannot find module '/opt/sh'
/usr/lib/node_modules/@wdio/cli/node_modules/@wdio/config/build/lib/ConfigParser.js:86
      throw e;
      ^

Error: Cannot find module '/opt/sh'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at ConfigParser.addConfigFile (/usr/lib/node_modules/@wdio/cli/node_modules/@wdio/config/build/lib/ConfigParser.js:51:48)
    at new Launcher (/usr/lib/node_modules/@wdio/cli/build/launcher.js:33:23)
    at launch (/usr/lib/node_modules/@wdio/cli/build/run.js:87:20)
    at run (/usr/lib/node_modules/@wdio/cli/build/run.js:64:12)
    at Object.run (/usr/lib/node_modules/@wdio/cli/build/index.js:45:20)
    at Object.<anonymous> (/usr/lib/node_modules/@wdio/cli/bin/wdio.js:11:21)

**Comment by horsecoin** [comment]
Never mind! OMG this looks cool! Will try!
2019-04-30 18:52:46 ☆  nickademous in ~
± |master ↑1 ↓2 S:387 U:367 ?:452 ✗| → docker run -it -v $(pwd):/usr/workspace blueimp/wdio

=========================
WDIO Configuration Helper
=========================

? Where should your tests be launched (Use arrow keys)
❯  local - https://www.npmjs.com/package/@wdio/local-runner

**Comment by blueimp** [comment]
Glad you like the setup! ☺️

**Comment by sayurimizuguchi** [comment]
For me the fix was changing 

#### from 
```javascript

require('ts-node/register');
```

#### to

```javascript

require('ts-node');
```
